# Generated by Django 4.2.3 on 2023-08-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
