# Generated by Django 4.2.3 on 2023-08-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='toss_order_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
